esphome:
  name: esp8266-1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "P/wcNwhcJdzyR4Nq38TT1U/1QCjBoqKKWECAy4nN5eY="

ota:
  password: "36785e723f3658ddea0af7050a95c25f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-1 Fallback Hotspot"
    password: "DYdwOtwh4ymV"

captive_portal:

switch:
  - platform: gpio
    name: "ESP8266 LED"
    pin: 2